package lab3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import lab3.models.ProductPage;
import lab3.utils.Util;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.time.Duration;
public class AddtocartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = Util.createDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    Util.quitDriver(driver);
  }

  @Test
  public void addtocart() {
    ProductPage productPage = new ProductPage(driver, "/p/mp002xw1dgzb/shoes-litebymascotte-krossovki/");
    productPage.chooseSize("36");
    productPage.addToCart();
    productPage.goToCart();
    
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    
    WebElement productElement = wait.until(ExpectedConditions.visibilityOfElementLocated(
        By.xpath("//*[contains(text(),'Mascotte')]")));
    
    assertTrue("товар не отображается", productElement.isDisplayed());
    
    WebElement sizeElement = driver.findElement(By.xpath("//*[contains(text(), '36 RUS')]"));
    assertTrue("размер не отображается", sizeElement.isDisplayed());
  }
}