package lab3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.WebDriver;
import lab3.models.ProductPage;
import lab3.utils.Util;

import org.openqa.selenium.By;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class AddtofavoritesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = Util.createDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("https://www.lamoda.ru");
    driver.manage().window().maximize();

    Cookie sidCookie = new Cookie.Builder("sid", "MGUzMTNjZTNhODgwMWFhZmY1MjM1Y2FiYjQwNjUwMzk=|1780944463|e25604f1a95d916db7a8b899cf737318c057f79a")
            .domain(".lamoda.ru")
            .path("/")
            .isSecure(false)
            .isHttpOnly(false)
            .build();
    driver.manage().addCookie(sidCookie);
    
    // Cookie: sessionId
    Cookie sessionIdCookie = new Cookie.Builder("Session_id", "3:1780765320.5.0.1769453059970:Mzk-XA:3983.1.2:1|936191851.-1.2.3:1769453059|3:11954684.903077._FkZx655mvIOxZU45ZiWV4-TdFc")
            .domain(".lamoda.ru")
            .path("/")
            .isSecure(false)
            .isHttpOnly(false)
            .build();
    driver.manage().addCookie(sessionIdCookie);

    driver.navigate().refresh();

    boolean loggedIn = !driver.findElements(
      By.xpath("//a[@href='/sales/order/history/']")
    ).isEmpty();

    System.out.println("Logged in = " + loggedIn);

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }

  @After
  public void tearDown() {
    Util.quitDriver(driver);
  }

  @Test
  public void addtofavorites() {
    ProductPage productPage = new ProductPage(driver, "/p/mp002xw1dgzb/shoes-litebymascotte-krossovki/");
    productPage.addToFavorites();
    assertTrue("Favorite action should change product controls", productPage.isFavorited());
  }
}
