package lab3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.assertTrue;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import lab3.models.ProductPage;
import lab3.utils.Util;
public class CheckreviewTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = Util.createDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    Util.quitDriver(driver);
  }

  @Test
  public void checkreview() {
    ProductPage productPage = new ProductPage(driver, "/p/mp002xw1dgzb/shoes-litebymascotte-krossovki/");
    productPage.openReviewsTab();

    assertTrue("отзывы не открыты", driver.findElement(By.xpath("//span[contains(@class, '_active_d5995_27') and @aria-label='Отзывы']")).isDisplayed());
  }
}
