package lab3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.assertTrue;
import org.openqa.selenium.WebDriver;

import lab3.models.MainPage;
import lab3.models.ResultsPage;
import lab3.utils.Util;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class FindproductTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = Util.createDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    Util.quitDriver(driver);
  }

  @Test
  public void findproduct() {
    MainPage mainPage = new MainPage(driver);

    String product = "nike";
    mainPage.findProduct(product);
    
    ResultsPage resultsPage = new ResultsPage(driver);
    
    assertTrue("нет результатов поиска", resultsPage.hasSearchResults());
    
    String currentUrl = driver.getCurrentUrl();
    
    assertTrue("неправильный url", currentUrl.contains(product) || currentUrl.contains("catalogsearch/result/?q=nike"));
    assertTrue("не те товары", resultsPage.resultsContainKeyword(product));
  }

  @Test
  public void findNonExistentProduct() {
    MainPage mainPage = new MainPage(driver);
    
    String product = "dsahdjshadjkhsajkdhjksahdksjahdkjashdkjashjk";
    mainPage.findProduct(product);
    
    ResultsPage resultsPage = new ResultsPage(driver);
    
    assertTrue("есть такие товары", resultsPage.isEmptyResultsMessageDisplayed());
  }
}