package lab3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.WebDriver;

import lab3.models.MainPage;
import lab3.utils.Util;

import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = Util.createDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    Util.quitDriver(driver);
  }
  @Test
  public void login() {
    MainPage mainPage = new MainPage(driver);

    mainPage.openLogin();
    mainPage.writePhoneNumber("9136771894");
    assertTrue(!mainPage.isLoginErrorDisplayed());
    
    try {
      Thread.sleep(20000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    assertTrue(mainPage.isProfileDisplayed());
  }
}
