package lab3;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.WebDriver;

import lab3.models.ArticlePage;
import lab3.models.JournalPage;
import lab3.models.MainPage;
import lab3.utils.Util;

import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class SelectarticleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = Util.createDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    Util.quitDriver(driver);
  }
  
  @Test
  public void selectarticle() {
    MainPage mainPage = new MainPage(driver);
    JournalPage journalPage = mainPage.goToJournals();

    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    System.out.println("Current URL: " + driver.getCurrentUrl());
    assertTrue(driver.getCurrentUrl().contains("/blog"));
    System.out.println(driver.getCurrentUrl());

    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    journalPage.openFirstArticle();
    ArticlePage articlePage = new ArticlePage(driver);
    System.out.println(driver.getCurrentUrl());

    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    assertTrue(articlePage.hasLink());
  }
}
